import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { motion } from 'framer-motion';
import ProductCard from './ProductCard';
import useViewStore from '../store/useViewStore';

const API_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api';

const RecommendationCarousel = () => {
  const { recentlyViewed } = useViewStore();
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchRecommendations = async () => {
      setLoading(true);
      try {
        const viewIds = recentlyViewed.map(v => v._id);
        const { data } = await axios.post(`${API_URL}/products/recommend`, { viewIds });
        setRecommendations(data);
      } catch (error) {
        console.error('Failed to fetch AI recommendations', error);
      } finally {
        setLoading(false);
      }
    };
    
    if (recentlyViewed.length > 0) {
      fetchRecommendations();
    }
  }, [recentlyViewed]);

  if (recentlyViewed.length === 0) return null;

  return (
    <div className="py-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 border-t border-[rgb(var(--foreground))]/10 mt-16">
      
      {/* Recently Viewed */}
      <h2 className="text-3xl font-heading font-bold uppercase tracking-tighter mb-8 bg-gradient-to-r from-gray-200 to-gray-500 bg-clip-text text-transparent">
        Recently Viewed
      </h2>
      <div className="flex overflow-x-auto gap-6 pb-8 snap-x">
        {recentlyViewed.map(product => (
          <div key={`recent-${product._id}`} className="min-w-[250px] snap-start">
            <ProductCard product={product} />
          </div>
        ))}
      </div>

      {/* AI Recommendations */}
      {recommendations.length > 0 && (
        <div className="mt-16">
          <h2 className="text-3xl font-heading font-bold uppercase tracking-tighter mb-4">
            You Might Also Like
          </h2>
          <p className="text-sm text-gray-500 uppercase tracking-widest font-mono mb-8">Generated by AI based on your taste</p>
          
          {loading ? (
            <div className="animate-pulse flex gap-6">
              {[1,2,3,4].map(i => <div key={i} className="min-w-[250px] aspect-[3/4] bg-white/5"></div>)}
            </div>
          ) : (
            <div className="flex overflow-x-auto gap-6 pb-8 snap-x">
              {recommendations.map(product => (
                <div key={`rec-${product._id}`} className="min-w-[250px] snap-start">
                  <ProductCard product={product} />
                </div>
              ))}
            </div>
          )}
        </div>
      )}
      
    </div>
  );
};

export default RecommendationCarousel;
